# Generated by Django 4.0.5 on 2022-06-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('planId', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=256, null=None)),
                ('amountOption', models.TextField(null=None)),
                ('tenureOption', models.TextField(null=None)),
                ('benefitPercentage', models.FloatField(null=None)),
                ('benefitType', models.CharField(max_length=256, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotionId', models.AutoField(primary_key=True, serialize=False)),
                ('promotionType', models.CharField(max_length=256, null=None)),
                ('promotionStartDate', models.DateTimeField()),
                ('promotionEndDate', models.DateTimeField()),
                ('promotionCount', models.IntegerField(null=None)),
                ('promotionBenefitPercentage', models.FloatField(null=None)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving_plans_apps.plans')),
            ],
        ),
    ]
