# Generated by Django 4.0.5 on 2022-06-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plans_apps', '0002_user_plans_is_active_promotions_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promotionCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promotionEndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promotionStartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
