# Generated by Django 4.0.5 on 2022-06-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plans_apps', '0003_alter_promotions_promotioncount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoal',
            name='promotionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saving_plans_apps.promotions'),
        ),
    ]
