# Generated by Django 4.0.5 on 2022-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plans_apps', '0004_alter_customergoal_promotionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoal',
            name='promotionId',
            field=models.IntegerField(null=True),
        ),
    ]
