# Generated by Django 4.0.5 on 2022-06-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_plans_apps', '0005_alter_customergoal_promotionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergoal',
            old_name='startDat',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='customergoal',
            name='id',
        ),
        migrations.AddField(
            model_name='customergoal',
            name='customerId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
